### ISSUE TITLE
Make height/width fit screen

### ISSUE THREAD

**Issue by yarnball** [cameronbourke/react-cardstack#10]
Hi,

Nice work on this. I'd like to make this mobile response. So is there a way to make it fit 100% height/width?

As per your instructions, the refinements seem to be in pixels.

**Comment by rawbknalb** [comment]
100% width works for me by passing `null` for the width prop

`<CardStack height={400} width={null} hoverOffset={25}>
            {renderStack}
  </CardStack>
`
