### ISSUE TITLE
Adding a Card to CardStack after initial render doesn't rerender correctly

### ISSUE THREAD

**Issue by evliu** [cameronbourke/react-cardstack#13]
Hi, I'm trying to dynamically grab data to populate new cards and insert them into the `CardStack`, but when I do, CardStack doesn't seem to rerender correctly with the new Cards. Here's example code that can reproduce the issue. Thoughts anyone? Thx!

```js
import React, { Component } from 'react';
import { CardStack, Card } from 'react-cardstack';
import { render } from 'react-dom';

class App extends Component {
	constructor(props) {
		super(props);
		this.state = { asdf: [] };
	}

	componentWillMount() {
		this.setState({ asdf: [{ a: 1 }, { a: 2 }, { a: 3 }] });
		setTimeout(() => this.setState({ asdf: [{ a: 3 }, { a: 2 }, { a: 1 }, { a: 0 }] }), 2000);
	}

	render() {
		const a = this.state.asdf.map(obj => {
			return <Card key={obj.a}><h2>{obj.a}</h2></Card>
		});

		return (
			<CardStack height={700}>
				{a}
			</CardStack>
		)
	}
}

render(<App />, document.getElementById('root'));
```

**Comment by evliu** [comment]
I found a workaround. I just set the key of `CardStack` to a property or state, and if that property or state changes, it rerenders `CardStack`

**Comment by cameronbourke** [comment]
@evliu Great idea! I'll be sure to address this in the next release, and at worse document this use case.
