### ISSUE TITLE
Can't Resolve ./Cardstack

### ISSUE THREAD

**Issue by SantiagoMoyano** [cameronbourke/react-cardstack#19]
When you run yarn dev, with the module already installed, it throws the error 

> Can't Resolve ./Cardstack....

Its because in dist/index.js , it exports like this:

`var _Cardstack = _interopRequireDefault(require("./Cardstack"));`

shoulde be:

`var _Cardstack = _interopRequireDefault(require("./CardStack"));`

**Comment by maitrucquynhq111** [comment]
I have a same problem.

**Comment by playerthong** [comment]
I have same problem , it seems author still not fix this bug Y_Y

**Comment by sharstream** [comment]
The same here.

**Comment by AshalathaP** [comment]
I am also facing the same issue. The way i resolved is as mentioned by "SantiagoMoyano".

**Comment by AshalathaP** [comment]
if you notice in node_modules/react-cardstack/dist/index.js file you will notice that the issue is while exporting the file, the name is mentioned as

**Comment by cameronbourke** [comment]
@AshalathaP Big thank you for taking this up apon yourself! I've been away from Github for the best part of 6 months now and have only just got back.
