### ISSUE TITLE
Uncaught Error: CardStack component must have at least two child Card components. Please check the children of this CardStack instance.     at new CardStack (CardStack.js:14)

### ISSUE THREAD

**Issue by miriam-z** [cameronbourke/react-cardstack#21]
When trying to populate with new data with example api 

https://itunes.apple.com/us/rss/topalbums/limit=100/json: 

and changed App into Component with ComponenDidMount:

    componentDidMount() {

        console.log("This is new test webpack");

        axios({
            method: 'GET',
            url: 'https://itunes.apple.com/us/rss/topalbums/limit=100/json',
            // url: 'http://localhost:4000/data',
            responseType: 'json',
        })
            .then(res => {

                this.setState({entry: res.data.feed.entry});
                console.log("this is res.data.feed.entry[0].title", res.data.feed.entry[0].title);
                console.log("this is res.data.feed.entry[1].title", res.data.feed.entry[1].title);
                console.log("this is res.data.feed.entry[2].title", res.data.feed.entry[2].title);
            })
            .catch(err =>
                console.error("this is error caught in axios call", err))
    }

this is returned:

Uncaught Error: CardStack component must have at least two child Card components. Please check the children of this CardStack instance.
    at new CardStack (CardStack.js:14)

**Comment by cameronbourke** [comment]
@rlaferla Totally agree!! I've been away from Github for the best part of 6 months now and have only just got back. Please feel free to fork the repo to suit your design :)

**Comment by cameronbourke** [comment]
Hey @miriam-z, thanks for the issue! I'm going to close this issue due to inactivity 😀
