### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by rohit8080** [cameronbourke/react-cardstack#22]
How if we need autoscroll if the number of items in the list is more than 20 or 50 ?
can we have the fixed expanding of the individual item in the list?

**Comment by cameronbourke** [comment]
Hey @rohit8080, thanks for opening the issue! Unfortunately I'm not actively maintaining the repo anymore, so I'm going to close this for now. If you decide to create a PR, please feel free to reopen this!
