### ISSUE TITLE
Cardstack.js` does not match the corresponding path on disk `CardStack.js`.

### ISSUE THREAD

**Issue by tektutorial** [cameronbourke/react-cardstack#24]
from logs :-  Module not found: `C:\data\projects\.....\client\node_modules\react-cardstack\dist\Cardstack.js` does not match the corresponding path on disk `CardStack.js`.

I think, I found the reason.
In file index.js we have below line.
var _Cardstack = _interopRequireDefault(require("./**Cardstack**"));

but its should be 
var _Cardstack = _interopRequireDefault(require("./**CardStack**"));

and the actual js file name in "node_modules\react-cardstack\dist" is CardStack.js.

For time being, I renamed my local repo file Cardstack.js. But not how it will work once I will deploy my code in server.

Please mail me at tektutorialfeedback@gmail.com if anything is not clear!!

Thanks
tektutorial

**Comment by dzz828** [comment]
@cameronbourke could you please release this fix?

**Comment by madeleineostoja** [comment]
Also facing this issue, not sure why it was closed, makes the package unuseable
