### ISSUE TITLE
Click-handlers

### ISSUE THREAD

**Issue by brandonmp** [cameronbourke/react-cardstack#3]
Has anyone devised a simple way of giving each card an actual click-handler? 

I'm trying to fire an event whenever a user expands a card, and I need to pass the name of the card clicked to the event handler. 

I tried wrapping card contents in a div w/ an onClick function, but the div only covers about 50% of the clickable-header area. 

In this img, the div has a white background and the cards are alternating teal/not-teal. 
![image](https://cloud.githubusercontent.com/assets/14139991/13897016/ec5a7e7a-ed77-11e5-87c8-547e40852749.png)

Am considering using refs but I know those are supposed to be a last resort.

Any path of less resistance?

**Comment by brandonmp** [comment]
submitted PR to accomplish this

**Comment by cameronbourke** [comment]
@brandonmp Just noticed this issue on github, I'll get back to your PR shortly! Thanks for creating the issue :+1:

**Comment by cameronbourke** [comment]
@brandonmp One way to add click handlers to the card, or any components within the card is to simply add a click handler and give it the id in the function. To better illustrate that, take the below for example:

```
...
render() {
	return (
		const ids = [0, 1, 2, 3, 4, 5];

		<CardStack height={500} width={400} hoverOffset={25}>

			{ids.map((id) =>
				<Card>
					// click handler for the card
					<div style={height: '100%'} onClick={() => alert(id)}>
						Card Id: {id}
					</div>
				</Card>
			)}

		</CardStack>
	);
}
```

**Comment by brandonmp** [comment]
@cameronbourke the problem with that is that only the internal did is click able. The title bar at the top of the header (ie about 50% of the visible header) isn't click able. 

That was first thing I tried  but made clicking it seemingly unresponsive half the time (b/c user isn't clear on which portion is clickable or not)

**Comment by brandonmp** [comment]
Internal div* sorry, on mobile not sure how to edit.

**Comment by cameronbourke** [comment]
@brandonmp Is this a public or private repo? I'm happy to jump in have a look with the context of the project you are working on. I'd say throw it in a jsbin or codepen but I haven't got it set up with https://npmcdn.com/ yet.

**Comment by brandonmp** [comment]
ah sorry it's private repo :/  the code (when i had the click handler on the internal div) more or less mirrors your snippet, though.

if you look at the screencap in OP, in that code I set the internal div (the one that holds card content) background to white, and the card color to 2 diff't pastels (alternating).  

you can see the white div only goes halfway up the header, so i think the onClick is working as intended, but the div to which the handler is assigned just doesn't cover all of the area.

but i've been using the small change i submitted in the PR for a bit now and it seems to work w/o issue, so this isn't so pressing a concern for me now.

**Comment by cameronbourke** [comment]
Let me put this repo up on npmcdn over the weekend and you can chuck it in a codepen/jsbin if you'd like and I'd more than happy to have a look at it!

**Comment by cameronbourke** [comment]
@brandonmp Hey, `react-cardstack` is now up on npm cdn, https://npmcdn.com/react-cardstack@0.1.1/dist/react-cardstack.min.js, if you could create a codepen, or jsbin when you get a chance I'd love to resolve this issue!
