### ISSUE TITLE
React-Native. 

### ISSUE THREAD

**Issue by smooJitter** [cameronbourke/react-cardstack#5]
Curious to know what would it take to convert this to a react-native component

**Comment by cameronbourke** [comment]
@smooJitter Quickly thinking about it, probably not a whole lot. I've got to spend some time tomorrow on merging a PR for this repo so I'll play around with React Native and get back to you!

**Comment by smooJitter** [comment]
Awesome

**Comment by ahmed1490** [comment]
+1

**Comment by cameronbourke** [comment]
@ahmed1490 Okay I'll commit to getting a `react-native` version out over the next fortnight!

**Comment by alessandro-bottamedi** [comment]
+1

**Comment by cameronbourke** [comment]
Hey guys, I've made some good progress on getting a `react-native` version up and running. Expect an initial version in 2 days.

**Comment by cameronbourke** [comment]
Alright, give or take 6 days haha, but it is out and about now! https://github.com/cameronbourke/react-native-cardstack. Please open issues like you open Pokemon Go on your walk to work, love to get people's feedback.
