### ISSUE TITLE
Unable to install the lib

### ISSUE THREAD

**Issue by deveshmittal** [cameronbourke/react-cardstack#6]
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! react-cardstack@0.0.7 compile: `babel src/cardstack.jsx --out-file dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-cardstack@0.0.7 compile script 'babel src/cardstack.jsx --out-file dist/index.js'.
npm ERR! This is most likely a problem with the react-cardstack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src/cardstack.jsx --out-file dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-cardstack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-cardstack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/devesh/Desktop/ReactExamples/react-cardstack-dev/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! react-cardstack@0.0.7 prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-cardstack@0.0.7 prepublish script 'npm run compile'.
npm ERR! This is most likely a problem with the react-cardstack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-cardstack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-cardstack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/devesh/Desktop/ReactExamples/react-cardstack-dev/npm-debug.log

**Comment by cameronbourke** [comment]
Hey! Thanks for the issue. Is then when you are trying to develop the component locally, or just using it in your project?

Also, did it happen right after you ran `npm install react-cardstack --save`?

**Comment by cameronbourke** [comment]
Closing this as there hasn't been a response for a month.
